### ISSUE TITLE
About the double donated dataset

### ISSUE THREAD

**Issue by serdarenginoglu** [uci-ml-repo/ucimlrepo-feedback#22] opened 2022-05-06 08:22 UTC
To whom it may concern

I tried to donate the "Monolithic Columns in Troad and Mysia Region" dataset but failed. I request that the information entries for these two data sets be deleted so that I can try again. If editing is allowed, deleting one will suffice.

Best regards

Serdar Enginoğlu

**Comment by ap0nia** [comment] 2023-06-08 15:08
Duplicate of #4, which has been fulfilled.

**Closed by ap0nia** 2023-06-08 15:08 UTC
